### ISSUE TITLE
Licensing information and copyright statement

### ISSUE THREAD

**Issue by onlyjob** [stgeneral/redmine-collapsed-journals#2]
Please add copyright statement, something like

~~~~
Copyright 2014 Dmitry Babenko <myemail@github.com>
Copyright 2013 Jürgen Diez
~~~~

Adding licensing information is also necessary but Jürgen Diez needs to be contacted to agree on terms. Unfortunately I could not find his contact details.

Thank you.

**Comment by run2fail** [comment]
Seconding this request. This is a really nice plugin and its great that someone is willing to continue supporting it. Unfortunately, basically no one can use it because the license is unclear. Maybe you can clarify the situation with the original developer?

**Comment by stgeneral** [comment]
@run2fail feel free to contact the original developer. I've provided a link to the source where the original plugin was taken in the README file. That is all information about the original author I have.

**Comment by stgeneral** [comment]
Just to clarify things with license and copyright. I haven't found any contacts of the original author of the plugin. But if he will contact me I gladly discuss the licenses and copyrights.

**Comment by onlyjob** [comment]
Why is this issue closed? It should be re-opened until the problem is resolved...

**Comment by go2null** [comment]
Should be re-opened and tagged 'help-wanted' or '3rd-party' or some such.
